### ISSUE TITLE
Structurally Complete checklist

### ISSUE THREAD

**Issue by rhtyd** [shapeblue/primate#60]
The following match against old UI:
- [x] All navigation tabs and list views
- [x] Role-based nav and actions show/hide
- [x] All actions on all such list views (est. 2days)
- [x] Autogenerated form/views work for all such actions (est. 1-2days -> list of bugs/issues)
- [x] Icons on all the actions (est. 1 day)

**Comment by rhtyd** [comment]
Closing this as done cc @anuragaw 
This will need investigation/testing, which we can do later. The offerings/settings tabs need many customisation and don't have all the actions available yet.
